---
title: "Favourite statistics papers"
author: "Kathryn"
date: "July 14, 2016"
output: html_document
layout: post
tags: [research, statistics]
permalink: fav_papers
comments: yes
---
  
  
I've been having a great time at the <a href="https://biometricconference.org/">Biometrics Conference in Victoria, BC</a> (and not only because it's my hometown). I've been enjoying sessions that are very relevant to my research area, and also some new and very intruiging topics for me (e.g., Bayesian non-parametrics). In both cases, I've had to do some real-time discrete googling to follow some of the talks, and it's made me think about the set of papers that I tend to rely on and return to over and over. I think a lot of researchers and grad students have a set of papers like this. I'm going to compile mine (started below but will be updated), and adding a section of ones my colleagues recommend. Please contribute! Email or on twitter kt.morrison AT mail.mcgill.ca or @kathryn_tm

<!--more-->

Here are a few that I went straight to during the conference. I'll be adding to this later. 


[1] Efron, B., and Tibshirani, R. Bootstrap methods for standard errors, confidence intervals, and other measures of statistical accuracy. *Statistical Science* (1986), 54–75.

[2] Geyer, C. J. Practical Markov chain Monte Carlo. *Statistical Science* 7, 4 (1992), 473–483.

[3] Lumley, T., Diehr, P., Emerson, S., and Chen, L. The importance of the normality assumption
in large public health data sets. *Annual Review of Public Health* 23, 1 (2002), 151–169.

[4] Muff, S., Riebler, A., Rue, H., Saner, P., and Held, L. Bayesian analysis of measurement error models using INLA. *Journal of the Royal Statistical Society, Series C (Applied Statistics)* 64, 2 (2013), 231–252.

[5] Rue, H., Martino, S., and Chopin, N. Approximate Bayesian inference for latent Gaussian models by using integrated nested Laplace approximations. *Journal of the Royal Statistical Society: Series B (Statistical Methodology)* 71, 2 (2009), 319–392.

[6] Smith, A. F., and Roberts, G. O. Bayesian computation via the Gibbs sampler and related Markov chain Monte Carlo methods. *Journal of the Royal Statistical Society, Series B (Statistical Methodology)* (1993), 3–23.

[7] Wakefield, J., and Shaddick, G. Health-exposure modeling and the ecological fallacy. *Biostatistics* 7, 3 (2006), 438–455.


